apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: labs-ci-cd-apps 
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default 

  # Source of the application manifests
  source:
    repoURL: https://github.com/tylerauerbeck/labs-ci-cd
    targetRevision: "2.0"
    path: apps

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: labs-ci-cd

