apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hoverfly 
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default

  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas

  # Source of the application manifests
  source:
    repoURL: https://github.com/helm/charts
    targetRevision: master
    path: incubator/hoverfly

    # helm specific config
    helm:
      # Extra parameters to set (same as setting through values.yaml, but these take precedence)
#      parameters:
#      - name: "nginx-ingress.controller.service.annotations.external-dns\\.alpha\\.kubernetes\\.io/hostname"
#        value: mydomain.example.com

      # Release name override (defaults to application name)
      releaseName: hoverfly

#      valueFiles:
#      - values-prod.yaml
      
      # Values file as block file
#      values: |
#        ingress:
#          enabled: true
#          path: /
#          hosts:
#            - mydomain.example.com
#          annotations:
#            kubernetes.io/ingress.class: nginx
#            kubernetes.io/tls-acme: "true"
#          labels: {}
#          tls:
#            - secretName: mydomain-tls
#              hosts:
#                - mydomain.example.com

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: labs-ci-cd 

