apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube 
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/helm/charts
    targetRevision: master
    path: stable/sonarqube 

    helm:
      releaseName: sonarqube 

      valueFiles:
      - values.yaml
      
  destination:
    server: https://kubernetes.default.svc
    namespace: labs-ci-cd 

