apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/tylerauerbeck/labs-ci-cd
    targetRevision: "2.0"
    path: tooling/sonarqube

    # plugin specific config
    plugin:
      name: oc-template
      # environment variables passed to the plugin
      env:
        - name: TEMPLATE_NAME
          value: https://raw.githubusercontent.com/redhat-cop/openshift-templates/master/sonarqube/sonarqube-deploy.yml
        - name: PARAM_FILE
          value: app.params

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: labs-ci-cd
