apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-pipelines 
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/tylerauerbeck/labs-ci-cd
    targetRevision: "2.0"
    path: tooling/tekton

  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-pipelines 

