apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-pipelines 
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: https://github.com/tektoncd/pipeline
    targetRevision: v0.9.2
    path: config

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-pipelines 

